security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # for the Symfony profiler, etc.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider    # your user provider (e.g., Entity User provider)
            jwt:
                authenticator: app.custom_jwt_authenticator

    access_control:
        # Allow login without a token
        - { path: ^/api/login, roles: PUBLIC_ACCESS }

        # Allow user registration without a token
        - { path: ^/users, roles: PUBLIC_ACCESS, methods: [POST] }

        # Everything else requires authentication
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

