services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d/ssl.conf:/etc/nginx/conf.d/ssl-self.conf:ro

  php:
    volumes:
      - /opt/fkb-app:/var/www/html
